### ISSUE TITLE
error in aligned equations

### ISSUE THREAD

**Issue by jstac** [QuantEcon/TaxSmoothing#3]
@thomassargent30 @sebgraves 

If you look [here](https://github.com/QuantEcon/TaxSmoothing/blob/master/Tax_Smoothing_3.ipynb) after the first displayed equation, the {align*} environment (after "subject to constraints") doesn't seem to be displaying properly.

**Comment by sebgraves** [comment]
Thanks. I have fixed this issue in notebooks 1 and 3. The {align} environment works for me on Jupyter but doesn't seem to be understood by GitHub.

**Comment by jstac** [comment]
It looks fine [here](http://nbviewer.jupyter.org/github/QuantEcon/TaxSmoothing/blob/master/Tax_Smoothing_3.ipynb) now so I'm going to close this issue.
